tab_bar_style separator
tab_separator ""
tab_bar_min_tabs 1

tab_title_template "{fmt.fg.white}{fmt.bg.black}{title}{fmt.fg.default}{fmt.bg.default}"
active_tab_title_template "{fmt.fg.black}{fmt.bg.white}{title}{fmt.fg.default}{fmt.bg.default}"

active_tab_font_style normal

enabled_layouts splits, *

tab_title_template "{user_vars.slot if user_vars.slot else index}: {title}"

map alt+v launch --location=vsplit --cwd=current
map alt+t launch --location=hsplit --cwd=current

map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down
map alt+h     neighboring_window left
map alt+l     neighboring_window right
map alt+k     neighboring_window up
map alt+j     neighboring_window down

map alt+shift+left  layout_action move_to_screen_edge left
map alt+shift+right layout_action move_to_screen_edge right
map alt+shift+up    layout_action move_to_screen_edge up
map alt+shift+down  layout_action move_to_screen_edge down

map alt+shift+h     layout_action move_to_screen_edge left
map alt+shift+l     layout_action move_to_screen_edge right
map alt+shift+k     layout_action move_to_screen_edge up
map alt+shift+j     layout_action move_to_screen_edge down

map alt+1 kitten goto_or_create_tab.py 1
map alt+2 kitten goto_or_create_tab.py 2
map alt+3 kitten goto_or_create_tab.py 3
map alt+4 kitten goto_or_create_tab.py 4
map alt+5 kitten goto_or_create_tab.py 5
map alt+6 kitten goto_or_create_tab.py 6
map alt+7 kitten goto_or_create_tab.py 7
map alt+8 kitten goto_or_create_tab.py 8
map alt+9 kitten goto_or_create_tab.py 9
map alt+0 kitten goto_or_create_tab.py 10

map alt+shift+1 kitten move_to_or_create_tab.py 1
map alt+shift+2 kitten move_to_or_create_tab.py 2
map alt+shift+3 kitten move_to_or_create_tab.py 3
map alt+shift+4 kitten move_to_or_create_tab.py 4
map alt+shift+5 kitten move_to_or_create_tab.py 5
map alt+shift+6 kitten move_to_or_create_tab.py 6
map alt+shift+7 kitten move_to_or_create_tab.py 7
map alt+shift+8 kitten move_to_or_create_tab.py 8
map alt+shift+9 kitten move_to_or_create_tab.py 9
map alt+shift+0 kitten move_to_or_create_tab.py 10
